### ISSUE TITLE
Mongo orchestration failing on Evergreen

### ISSUE THREAD

**Issue by rstam** [10gen/mongo-orchestration#250] opened 2018-07-11 14:41 UTC
You can see the failures on this Evergreen build of the C# driver:

https://evergreen.mongodb.com/version/dot_net_driver_5df1c2aa26f83405d3f9491c2b0cd722e1f47439

There are 8 purple tasks. 2 for server 2.6, 2 for server 3.0 and 4 for latest server.

I believe the failures against the latest server are related to an issue that has already been reported and addressed. This issue is about the failures to spin up server version 2.6 and 3.0.

For the first failure with 2.6 I see the following error the the orchestration.log:

Exception: mongod --repair failed with exit code 100, check log file: c:\data\mci\5ca38892a6754b774e0437178d85007e\drivers-tools\.evergreen\orchestration\db\mongo-yhuc1i\mongod.log

and the following in the mongod.log:

2018-07-10T20:13:13.094+0000 [initandlisten] options: { repair: true, storage: { dbPath: "c:\data\mci\5ca38892a6754b774e0437178d85007e\drivers-tools\.evergreen\orchestration\db\mongo-yhuc1i" }, systemLog: { destination: "file", logAppend: true, path: "c:\data\mci\5ca38892a6754b774e0437178d85007e\drivers-tools\.evergreen\orchestration\db\mongo-yhuc1i\mongod.log" } }
2018-07-10T20:13:13.095+0000 [initandlisten] exception in initAndListen: 12596 old lock file, terminating

And the cluster never spins up.

**Comment by behackett** [comment] 2018-07-12 15:43
I think this problem is fixed by https://github.com/10gen/mongo-orchestration/pull/248

Reopen this ticket if you continue to see problems.

**Comment by rstam** [comment] 2018-07-12 15:58
I restarted one of the failed tasks and still got the same error. See:

https://evergreen.mongodb.com/task_log_raw/dot_net_driver_tests__version~2.6_os~windows_64_topology~sharded_cluster_auth~auth_ssl~ssl_test_a1742b3777cb4872f8d03591afe76bb054e468c7_18_07_10_20_45_45/1?type=T#L530

**Comment by ShaneHarvey** [comment] 2018-07-23 19:09
I think this must be caused by #248. The following error happens when restarting the 2.6 config server:
```
2018-07-23 17:39:45,809 [INFO] mongo_orchestration.servers:395 - Sending kill signal to C:/data/mci/ab8741bc2f0037b8e2b94b26787b9429/drivers-tools/mongodb/bin\mongod on port 1026
2018-07-23 17:39:45,815 [INFO] mongo_orchestration.servers:332 - Performing repair on locked dbpath c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\db\mongo-qnvnvo
2018-07-23 17:39:45,842 [INFO] mongo_orchestration.process:173 - repair output: ************** 

2018-07-23 17:39:46,842 [INFO] mongo_orchestration.process:173 - repair output: You specified --repair but there are dirty journal files. Please

2018-07-23 17:39:46,842 [ERROR] mongo_orchestration.apps:68 - <function sh_create at 0x00000000024BFC88>
Traceback (most recent call last):
  File "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\apps\__init__.py", line 66, in wrap
    return f(*arg, **kwd)
  File "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\apps\sharded_clusters.py", line 68, in sh_create
    result = _sh_create(data)
  File "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\apps\sharded_clusters.py", line 44, in _sh_create
    cluster_id = ShardedClusters().create(params)
  File "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\sharded_clusters.py", line 477, in create
    cluster = ShardedCluster(params)
  File "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\sharded_clusters.py", line 186, in __init__
    restart_with_auth(self.configdb_singleton._storage[config_id])
  File "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\sharded_clusters.py", line 183, in restart_with_auth
    server_or_rs.restart(config_callback=add_auth)
  File "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\servers.py", line 406, in restart
    return self.start(timeout)
  File "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\servers.py", line 333, in start
    process.repair_mongo(self.name, self.cfg['dbpath'])
  File "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\process.py", line 178, in repair_mongo
    "check log file: %s" % (return_code, log_file))
Exception: mongod --repair failed with exit code 100, check log file: c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\db\mongo-qnvnvo\mongod.log
```
And the 2.6 log file:
```
2018-07-23T17:39:45.837+0000 ***** SERVER RESTARTED *****
2018-07-23T17:39:45.841+0000 Hotfix KB2731284 or later update is not installed, will zero-out data files
2018-07-23T17:39:45.841+0000 [initandlisten] MongoDB starting : pid=3204 port=27017 dbpath=c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\db\mongo-qnvnvo 64-bit host=WIN-CUH0BN4DPR0
2018-07-23T17:39:45.841+0000 [initandlisten] targetMinOS: Windows 7/Windows Server 2008 R2
2018-07-23T17:39:45.841+0000 [initandlisten] db version v2.6.12
2018-07-23T17:39:45.841+0000 [initandlisten] git version: d73c92b1c85703828b55c2916a5dd4ad46535f6a modules: enterprise
2018-07-23T17:39:45.841+0000 [initandlisten] OpenSSL version: OpenSSL 1.0.1p-fips 9 Jul 2015
2018-07-23T17:39:45.841+0000 [initandlisten] build info: windows sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1') BOOST_LIB_VERSION=1_49
2018-07-23T17:39:45.841+0000 [initandlisten] allocator: system
2018-07-23T17:39:45.841+0000 [initandlisten] options: { repair: true, storage: { dbPath: "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\db\mongo-qnvnvo" }, systemLog: { destination: "file", logAppend: true, path: "c:\data\mci\ab8741bc2f0037b8e2b94b26787b9429\drivers-tools\.evergreen\orchestration\db\mongo-qnvnvo\mongod.log" } }
2018-07-23T17:39:45.842+0000 [initandlisten] exception in initAndListen: 12596 old lock file, terminating
2018-07-23T17:39:45.842+0000 [initandlisten] dbexit: 
2018-07-23T17:39:45.842+0000 [initandlisten] shutdown: going to close listening sockets...
2018-07-23T17:39:45.842+0000 [initandlisten] shutdown: going to flush diaglog...
2018-07-23T17:39:45.842+0000 [initandlisten] shutdown: going to close sockets...
2018-07-23T17:39:45.842+0000 [initandlisten] shutdown: waiting for fs preallocator...
2018-07-23T17:39:45.842+0000 [initandlisten] shutdown: closing all files...
2018-07-23T17:39:45.842+0000 [initandlisten] closeAllFiles() finished
2018-07-23T17:39:45.842+0000 [initandlisten] dbexit: really exiting now
```

I think the problem is that [subprocess.Popen.terminate()](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.terminate) on Windows uses [TerminateProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686714(v=vs.85).aspx) which is akin to SIGKILL in Unix. This means that the mongod cannot do it's normal shutdown procedure and remove the "old lock file".

I think the simplest thing to do would be to revert back to using the shutdown command on < 4.0 since it was working fine until 4.0.

**Comment by ShaneHarvey** [comment] 2021-04-06 19:15
This was fixed by https://github.com/10gen/mongo-orchestration/pull/253.

**Closed by ShaneHarvey** 2021-04-06 19:15 UTC
